### ISSUE TITLE
It's crushed on Android 6.0

### ISSUE THREAD

**Issue by TommyTC** [BennyKok/OpenLauncher#1]
Hey buddy.
I try build this project and run it on Android 6.0,buy It will be crushed when you open other apps.
But your complied apk will not crush.

Here is stack trace:
`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.mkdir()' on a null object reference
                                                                          at android.app.ContextImpl.openFileOutput(ContextImpl.java:400)
                                                                          at android.content.ContextWrapper.openFileOutput(ContextWrapper.java:183)
                                                                          at com.bennyv4.project2.util.Tools.writeToFile(Tools.java:139)
                                                                          at com.bennyv4.project2.util.LauncherSettings.writeSettings(LauncherSettings.java:97)
                                                                          at com.bennyv4.project2.Home.onPause(Home.java:341)
                                                                          at android.app.Activity.performPause(Activity.java:6363)
                                                                          at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1311)
                                                                          at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3367)
                                                                          at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3340) 
                                                                          at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3315) 
                                                                          at android.app.ActivityThread.-wrap13(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                          at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117) `

**Comment by alorma** [comment]
Reading the exception, i not see gitskarios anywhere.

And, i see you use xposed framework, i don't support root devices.

**Comment by creativetrendsapps** [comment]
Works fine for me on 6.0.1 and I'm rooted as well. I built the project without issue.

**Comment by TommyTC** [comment]
I found the cause of this issue.
Without permission "READ / WRITE _EXTERNAL_STORAGE".

Thanks a lot for your answer.usually I can't get any answers because my English is so limited.

**Comment by BennyKok** [comment]
I will check it out, but the settings file should be written into internal storage but I am not sure.

**Comment by BennyKok** [comment]
I have added the permission, if you have time, try to compile it again and give it a go. Thx.

**Comment by scoute-dich** [comment]
Works here using Android 7.1.1 (also using icon pack, which also needs the permission).

**Comment by BennyKok** [comment]
So maybe I close this issue
