### ISSUE TITLE
Launcher Crashes when you drag a icon to the dock

### ISSUE THREAD

**Issue by TeamBrainStorm** [BennyKok/OpenLauncher#15]
When you go to add a app from the vertical app drawer or in all apps mode to the dock the app sometimes crashes here's the logcat:

```
02-04 10:52:52.061 15892-15892/com.benny.openlauncher E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.benny.openlauncher, PID: 15892
                                                                        java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Point.y' on a null object reference
                                                                            at com.benny.openlauncher.widget.CellContainer.getPeekDirectionFromCoordinate(CellContainer.java:84)
                                                                            at com.benny.openlauncher.widget.CellContainer.peekItemAndSwap(CellContainer.java:101)
                                                                            at com.benny.openlauncher.widget.Desktop.onDrag(Desktop.java:172)
                                                                            at android.view.View.callDragEventHandler(View.java:20898)
                                                                            at android.view.View.dispatchDragEvent(View.java:20889)
                                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1510)
                                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
                                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
                                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
                                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
                                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
                                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
                                                                            at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:5551)
                                                                            at android.view.ViewRootImpl.-wrap7(ViewRootImpl.java)
                                                                            at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3668)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)




I email Benny About it but wanted to open a issue in case another developer could look into it  


Thanks in advance!

```

**Comment by BennyKok** [comment]
Yeah,

**Comment by BennyKok** [comment]
Hey man check it out

**Comment by dkanada** [comment]
I dont know if @TeamBrainStorm is still having issues but I tried to replicate the issue again after your commits and it looks like it is working perfectly now, thanks for the fix.

**Comment by BennyKok** [comment]
Well good to hear that, thx for testing and the pull request @dkanada.

**Comment by TeamBrainStorm** [comment]
I am not seeing this issue any more I think you fixed it with that last update! i'll let you know if it starts doing it again!

**Comment by BennyKok** [comment]
Reopen this anytime
